{% set name = "hcephes" %}
{% set version = "0.4.1" %}
{% set sha256 = "82bae0311b347fd843f3cf45cbf96d3b3bd0157516cc372b99ccd2d8d4acdced" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/limix/hcephes/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - ninja  # [win]

test:
  commands:
    - test -e $PREFIX/lib/libhcephes.so                     # [linux]
    - test -e $PREFIX/include/hcephes.h                     # [unix]
    - test -e $PREFIX/lib/libhcephes.dylib                  # [osx]
    - if NOT exist %LIBRARY_LIB%/hcephes.lib exit 1         # [win]
    - if NOT exist %LIBRARY_BIN%/hcephes.dll exit 1         # [win]
    - if NOT exist %LIBRARY_INC%/hcephes.h exit 1           # [win]

about:
  home: https://github.com/limix/hcephes
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Netlib Cephes library'
  dev_url: https://github.com/limix/hcephes

extra:
  recipe-maintainers:
    - Horta
