{% set name = "hcephes" %}
{% set version = "0.3.3" %}
{% set sha256 = "0d2c362e7817461c75a3b0c7d5f149cbf6a814f7ed4a8ec0a8c88f49bb843781" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/limix/hcephes/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
  host:
    - conda-build

test:
  commands:
    - test -e $PREFIX/lib/libhcephes.so  # [linux]
    - test -e $PREFIX/lib/libhcephes.dylib  # [osx]
    - test -e $PREFIX/lib/libhcephes_static.a  # [unix]
    - if NOT exist %PREFIX%/lib/hcephes.lib exit 1  # [win]
    - if NOT exist %PREFIX%/lib/hcephes.dll exit 1  # [win]
    - if NOT exist %PREFIX%/lib/hcephes_static.lib exit 1  # [win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/limix/hcephes
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Cephes library'
  doc_url: https://github.com/limix/hcephes
  dev_url: https://github.com/limix/hcephes

extra:
  recipe-maintainers:
    - Horta
