{% set name = "hcephes" %}
{% set version = "0.2.0" %}
{% set sha256 = "bb46e8dc34352f45b5eb4791d8af58dc22eaad5fc3dd1b05bfe1b2f99326f81f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/limix/hcephes/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  features:
    - vc9   # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]
    - vc14  # [win and py36]

requirements:
  build:
    - python  # [win]
    - toolchain
    - cmake
    - vc 9   # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
    - vc 14  # [win and py36]
  run:
    - vc 9   # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
    - vc 14  # [win and py36]

test:
  commands:
    - test -e $PREFIX/lib/libhcephes.so  # [linux]
    - test -e $PREFIX/lib/libhcephes.dylib  # [osx]
    - test -e $PREFIX/lib/libhcephes_static.a  # [unix]
    - if NOT exist %PREFIX%/lib/hcephes.lib exit 1  # [win]
    - if NOT exist %PREFIX%/lib/hcephes.dll exit 1  # [win]
    - if NOT exist %PREFIX%/lib/hcephes_static.lib exit 1  # [win]

about:
  home: https://github.com/limix/hcephes
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Cephes library'
  doc_url: https://github.com/limix/hcephes
  dev_url: https://github.com/limix/hcephes

extra:
  recipe-maintainers:
    - Horta
