travis:
  secure:
    BINSTAR_TOKEN: ZPkmZ2tJmzwb6zlPXdSYx+y3TbRrwQEUYZ4KIc9y4NmK8IRE2uvhOnXnpSry4VLzxBkyvgt3iBPQZcGCxu28wX1VDEsKhkJfN1lg7yV//1qmb69tHknOYYOG/9h6sqwr7oWlDskUxRW2Cujxd8VeiuN0DOkfFYPM0y1NhaiviOy84xUcgDJS0LKMd1R8mYkE5N53kTQjrDfARW24hx7RVuux1HOAOaRA7OWZCBxI6oxXVXqLG3ZqlUsMuRTuWkVEF+2aaUf+JFIsrEe/YTJ1WwFaAXTht8qXbieRV8axeg2Mi171i5OSxTS1PIGczdnfzxnpUpn2qkKxqvoUxBQ7GY5AgjDWdzw6piLvFgq/MqWbEkLwARQMoJRoMOKsqyyPVm4W5lBT+nx6kt2bagFgy38GzfbtcFsRzLFDuCGzgh0hYfkmOQpZSMtdLaq5POTAHkHZGxUZrxFnMFh9Og1KDGAR06pDRe41dEoZnqF3WURY7dUFY1kdSkFzJMuy6tWtEE9+tiQHKsVFovBQaAbXbLYo431aBCiuH9gvCCchtyWv+zt+TZymi0rcsS972A9dpRdc28htHClcXcg+2EcaROPewFpLVcQ+fgbqW0HFEj4Un/PR0MmeQOmty0ABBN90gKKAmWRkdj5uEQWJCM91/Zr6nNL/lTjA5rMxgZLWExs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
