travis:
  secure:
    BINSTAR_TOKEN: aCURT54wYo8kkQfApi2BCOpkuSthg7SBRBldjZUzC4a6dTmfRSSfxXhAFJ1NMG+ZmC45gk+ntqeNJLGiOXJta+8sAykumEB/7T1B8RQcqvwAo8vZ2FzmlkonafHI/oWJGIOzIE+aU6HtLN5oTY0q6EbiFtOtHXfSvW5ulo+VuMeKzJ9+QfHEsXcUL47cCVxCYOz7L4Nyn13QWYpf4fMaaTDWZMvtgyeWz49Ipbg5tvm6AuSIKqQTWbbNwG/l4mnnqE/z+L7J9I4YHo3CYtfdyXHExTCJb72SVlpW9gZQ7AW0+t7LqzUkFvt16KXTHC335m2eG4M7mJAVs0mWJJWZ5YryFFJFVkCkHw3hHALStli5Vwriyd4OS7dO90rXBt5Kbsq2Uyk/ntJ8h3r1rzfL/fD1oQNTj7BJMcO3he3Wacu+wMCi2X2y8AYLHmA8RBDmde8JHQFksgB3bABBJrAeqMJwtFsyEKfRKDtnlcx3O0fGOFmHiBanIMy0NifWLPy63iVrMUeg1g49MGoADsGdP15mwZKc7C+aG7wvhuJEDHLeXbxe2W0q6+eBq39x/lez4qj/jqZS5mYTOES3KYKrCLORgw0d61UDOIMQHIHUFD18DYp2B+csCUUeDlk3tyTVLuWPFUehf0vGJe8VqKbagtXGbv8vuGF/CKe5wGw+nuA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
